In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## Create & Read 

### 1D Array 

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

5

 ### 2D array 

In [11]:
arr2 = np.array([[1,2,3,4], [5, 6, 7, 8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim


2

In [13]:
arr2.shape

(2, 4)

In [14]:
arr2.dtype

dtype('int32')

In [15]:
arr2.size

8

### 3D array 

In [21]:
arr3 = np.array([[[1,2,3,4], [5, 6, 7, 8]], [[1,2,3,4], [5, 6, 7, 8]],[[1,2,3,4], [5, 6, 7, 8]]])

In [22]:
arr3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [23]:
arr3.ndim


3

In [24]:
arr3.shape

(3, 2, 4)

### Create random Array 

In [25]:
randomarr = np.random.rand(3,2,3)
randomarr

array([[[0.14108587, 0.71541383, 0.36748382],
        [0.2009905 , 0.74669521, 0.54424965]],

       [[0.21531398, 0.29501844, 0.16564698],
        [0.63060521, 0.98351739, 0.34212894]],

       [[0.44779653, 0.39489783, 0.3254716 ],
        [0.74845385, 0.45275121, 0.19346037]]])

In [26]:
random.dtype

NameError: name 'random' is not defined

In [27]:
randomarr.dtype

dtype('float64')

In [34]:
zerosarr = np.zeros((2,3,3))

In [36]:
zerosarr = np.zeros((2,3,3))
zerosarr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
zerrosarr.dtype

NameError: name 'zerrosarr' is not defined

In [38]:
zerosarr.dtype

dtype('float64')

In [40]:
full = np.full((3,4,5,), 3)
full

array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])

In [41]:
full[0]

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [42]:
full[0,1]

array([3, 3, 3, 3, 3])

In [43]:
arr3[0:2]

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [44]:
arr3[-1]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
arr3[1,1,2]

7

In [46]:
arr3[1,0,1]

2

In [1]:
arr11 = np.random.rand(2,3,4)
arr22 = np.random.rand(2,3,4)


NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
arr11 = np.random.rand(2,3,4)
arr22 = np.random.rand(2,3,4)

In [4]:
arr11

array([[[0.11178594, 0.36501197, 0.08350767, 0.52646022],
        [0.35299209, 0.63139686, 0.85296328, 0.97899952],
        [0.03599461, 0.12162636, 0.30279864, 0.69989252]],

       [[0.32512826, 0.3167462 , 0.03823437, 0.48797278],
        [0.62664942, 0.92458874, 0.28951815, 0.73025586],
        [0.02696633, 0.85763852, 0.93542165, 0.63229223]]])

In [5]:
arr22

array([[[0.16654816, 0.24645666, 0.32705039, 0.15452074],
        [0.22052829, 0.84170749, 0.15079081, 0.09322322],
        [0.29646111, 0.62432361, 0.02465109, 0.96134432]],

       [[0.20274142, 0.62641095, 0.19754428, 0.5247976 ],
        [0.56530738, 0.5377514 , 0.33370789, 0.86177588],
        [0.07622641, 0.85327966, 0.0435209 , 0.60316475]]])

### BASIC Math Oparations 

In [6]:
np.add(arr11, arr22)

array([[[0.2783341 , 0.61146863, 0.41055806, 0.68098095],
        [0.57352038, 1.47310435, 1.00375409, 1.07222275],
        [0.33245571, 0.74594997, 0.32744973, 1.66123684]],

       [[0.52786968, 0.94315715, 0.23577865, 1.01277038],
        [1.1919568 , 1.46234014, 0.62322605, 1.59203174],
        [0.10319273, 1.71091818, 0.97894255, 1.23545698]]])

In [7]:
np.subtract(a1, a2)

NameError: name 'a1' is not defined

In [8]:
np.subtract(arr11, arr22)

array([[[-0.05476223,  0.11855532, -0.24354272,  0.37193948],
        [ 0.1324638 , -0.21031062,  0.70217247,  0.8857763 ],
        [-0.2604665 , -0.50269726,  0.27814755, -0.2614518 ]],

       [[ 0.12238684, -0.30966474, -0.15930992, -0.03682483],
        [ 0.06134203,  0.38683734, -0.04418974, -0.13152003],
        [-0.04926008,  0.00435887,  0.89190075,  0.02912748]]])

array([[[ 0.67119285,  1.48103921,  0.25533579,  3.4070522 ],
        [ 1.60066582,  0.75013811,  5.65659982, 10.50166997],
        [ 0.12141426,  0.194813  , 12.28337684,  0.72803522]],

       [[ 1.60365978,  0.50565241,  0.19354835,  0.92983042],
        [ 1.10851094,  1.71936091,  0.86757958,  0.84738488],
        [ 0.35376622,  1.00510837, 21.49361836,  1.04829109]]])

In [10]:
np.multiply(arr11, arr22)

array([[[0.01861774, 0.08995963, 0.02731122, 0.08134902],
        [0.07784474, 0.53145147, 0.12861903, 0.09126549],
        [0.010671  , 0.07593421, 0.00746432, 0.6728377 ]],

       [[0.06591696, 0.19841329, 0.00755298, 0.25608694],
        [0.35424954, 0.49719889, 0.09661449, 0.62931688],
        [0.00205555, 0.7318055 , 0.04071039, 0.38137639]]])

In [10]:
np.multiply(arr11, arr22)

array([[[0.01861774, 0.08995963, 0.02731122, 0.08134902],
        [0.07784474, 0.53145147, 0.12861903, 0.09126549],
        [0.010671  , 0.07593421, 0.00746432, 0.6728377 ]],

       [[0.06591696, 0.19841329, 0.00755298, 0.25608694],
        [0.35424954, 0.49719889, 0.09661449, 0.62931688],
        [0.00205555, 0.7318055 , 0.04071039, 0.38137639]]])

In [10]:
np.multiply(arr11, arr22)

array([[[0.01861774, 0.08995963, 0.02731122, 0.08134902],
        [0.07784474, 0.53145147, 0.12861903, 0.09126549],
        [0.010671  , 0.07593421, 0.00746432, 0.6728377 ]],

       [[0.06591696, 0.19841329, 0.00755298, 0.25608694],
        [0.35424954, 0.49719889, 0.09661449, 0.62931688],
        [0.00205555, 0.7318055 , 0.04071039, 0.38137639]]])

In [12]:
sqrt

5.0

In [13]:
abs

2

In [14]:
power

32

In [15]:
mins

0.026966327244369426

## Update `

In [16]:
arr3

NameError: name 'arr3' is not defined

In [17]:
arr2


NameError: name 'arr2' is not defined

In [18]:
arr11

array([[[0.11178594, 0.36501197, 0.08350767, 0.52646022],
        [0.35299209, 0.63139686, 0.85296328, 0.97899952],
        [0.03599461, 0.12162636, 0.30279864, 0.69989252]],

       [[0.32512826, 0.3167462 , 0.03823437, 0.48797278],
        [0.62664942, 0.92458874, 0.28951815, 0.73025586],
        [0.02696633, 0.85763852, 0.93542165, 0.63229223]]])

In [19]:
arr11[0, 0, 0]

0.11178593676054538

In [20]:
arr11[0, 0, 0] = 10

In [21]:
arr11

array([[[10.        ,  0.36501197,  0.08350767,  0.52646022],
        [ 0.35299209,  0.63139686,  0.85296328,  0.97899952],
        [ 0.03599461,  0.12162636,  0.30279864,  0.69989252]],

       [[ 0.32512826,  0.3167462 ,  0.03823437,  0.48797278],
        [ 0.62664942,  0.92458874,  0.28951815,  0.73025586],
        [ 0.02696633,  0.85763852,  0.93542165,  0.63229223]]])

In [24]:
arr11.sort()

In [25]:
arr11

array([[[ 0.08350767,  0.36501197,  0.52646022, 10.        ],
        [ 0.35299209,  0.63139686,  0.85296328,  0.97899952],
        [ 0.03599461,  0.12162636,  0.30279864,  0.69989252]],

       [[ 0.03823437,  0.3167462 ,  0.32512826,  0.48797278],
        [ 0.28951815,  0.62664942,  0.73025586,  0.92458874],
        [ 0.02696633,  0.63229223,  0.85763852,  0.93542165]]])

In [26]:
arr11.shape 

(2, 3, 4)

In [38]:
arr11_reshape = arr11.reshape(3,2,4)

In [39]:
arr11_reshape

array([[[ 0.08350767,  0.36501197,  0.52646022, 10.        ],
        [ 0.35299209,  0.63139686,  0.85296328,  0.97899952]],

       [[ 0.03599461,  0.12162636,  0.30279864,  0.69989252],
        [ 0.03823437,  0.3167462 ,  0.32512826,  0.48797278]],

       [[ 0.28951815,  0.62664942,  0.73025586,  0.92458874],
        [ 0.02696633,  0.63229223,  0.85763852,  0.93542165]]])

### APPENDING Arr 

In [49]:
zero = np.zeros([4,3,3])

In [45]:
zero

array([0., 0., 0., 0.])

In [48]:
newarr = np.ones([3,4,5])

In [50]:
newarr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [53]:
array = np.append(newarr, newarr, axis=0)

In [54]:
array

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [60]:
result_array = np.insert(array, 4, newarr, axis=0)
result_array

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1.,

# Delete

In [61]:
np.delete(result_array, 0, axis=1)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [62]:
np.save("neew array", result_array)

In [63]:
np.load("neew array.npy")

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1.,